epos:
  ros__parameters:
    device_name: "EPOS4"
    protocol: "MAXON SERIAL V2"
    interface: "USB"
    portname: "USB0"

    use_sub_device: true
    sub_device_name: "EPOS4"
    sub_device_protocol: "CANopen"

    auto_enable: true
    dataout_freq: 10

    motor_id: [1]
    motor_id_on_sub: [2]

dynamixel:
  ros__parameters:
    portname: "/dev/ttyUSB0"
    baudrate: 115200
    ids: [2, 3, 4, 5]
