name: Build and Deploy ROS 2 Packages with Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  release:
    types: [published]

jobs:
  build_ros2:
    strategy:
      matrix:
        rosdistro: [ humble ]

    runs-on: ubuntu-latest

    continue-on-error: true

    container:
      image: ros:${{ matrix.rosdistro }}-ros-base

    steps:
    - uses: actions/checkout@v2
      with:
        path: src/osp_naive

    - name: Install dependencies
      run: apt -y update
      
    - name: Install vcs and additional dependencies
      run: apt -y install python3-vcstool curl

    - name: Clone external dependencies
      run: |
        vcs import --input depends.rosinstall --recursive src


    - name: Install ROS dependencies
      run: |
        rosdep update
        rosdep install -r -y -i --from-paths .

    - name: Build tests
      id: build_test
      run: . /opt/ros/${{ matrix.rosdistro }}/setup.sh && colcon build --event-handlers console_cohesion+
      continue-on-error: true

    - name: build_test command success
      if: steps.build_test.outcome == 'success'
      run: echo "result - success"

    - name: build_test command failure
      if: steps.build_test.outcome == 'failure'
      run: echo "result - failure" && exit 1
